name: Python

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  pyinstaller:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          'ubuntu-22.04', 'ubuntu-22.04-arm',
          'windows-latest', 'windows-11-arm',
          'macos-13', 'macos-14'
        ]
      fail-fast: false
      max-parallel: 3

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Legendary dependencies and build tools
      run: pip3 install --upgrade
        setuptools
        pyinstaller
        requests
        filelock

    - name: Optional dependencies (WebView)
      run: pip3 install --upgrade pywebview
      if: runner.os != 'macOS'

    - name: Set strip option on non-Windows
      id: strip
      run: echo "option=--strip" >> $GITHUB_OUTPUT
      if: runner.os != 'Windows'

    - name: Build
      working-directory: legendary
      run: pyinstaller
        --onefile
        --name legendary
        ${{ steps.strip.outputs.option }}
        -i ../assets/windows_icon.ico
        cli.py
      env:
        PYTHONOPTIMIZE: 1

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-package
        path: legendary/dist/*
